// <auto-generated />
namespace Arysoft.WebsiteMVC.Basico.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreacionInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreacionInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201701062358526_CreacionInicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
